[project]
name = "greeter"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = ["pulumi>=3.170.0,<4.0.0", "pulumi_random>=4.0,<5.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
